### ISSUE TITLE
publish to MELPA (or ELPA)?

### ISSUE THREAD

**Issue by stapelberg** [russell/cue-mode#1]
Thanks for providing this package!

Could you please publish it to MELPA (probably easiest) or ELPA (longer-term?) so that I can install it using package.el?

**Comment by russell** [comment]
good point, i'll get it added over easter

**Comment by nipuna-perera** [comment]
looking for this also!

**Comment by russell** [comment]
awesome!  there is an open PR upstream https://github.com/melpa/melpa/pull/7994 so should be soon

**Comment by russell** [comment]
The PR to add this to melpa just merged, i don't know how long it will take to show up in the archive, but i'll close this once i have confirmed it is there and working

**Comment by stapelberg** [comment]
I was just able to install the package from MELPA. Thanks for getting this done!
